### ISSUE TITLE
Regarding code release

### ISSUE THREAD

**Issue by Anirudh257** [EgocentricVision/RNA-TTA#1]
Congratulations on the excellent work! I would love to know more and understand the code. When can it be released?

**Comment by EgocentricVision** [comment]
Thank you for your interest in my work; unfortunately, I am still working on it and it is not yet ready for release, but I have recently uploaded a file called loss.py that contains all of the losses. As regards the models, there are the standard I3D and the BnInception models implemented in the late fusion approach, which should be easy to implement.

Moreover, I hope that the loss can help you to effectively use it.

If you have any problems, please contact me at mirco.planamente@polito.it, and I will do my best to assist you.

**Comment by Anirudh257** [comment]
Cool, looking forward to the code, Grazie!
